Issues/1988@v5 fix css style
bem/bem-components pull request #1989
Opened 2016-12-20 21:01 UTC by belozer

fix #1988

2016-12-20 21:22 UTC, tadatuta requested changes

2016-12-20 21:22 UTC, tadatuta commented on common.blocks/z-index-group/z-index-group.examples/10-z-index-group.blocks/popup/_size/popup_size_bigger.css
> +:block(popup):mod(size bigger) {
здесь еще расширение файла нужно поправить

2016-12-20 22:20 UTC, belozer commented on common.blocks/z-index-group/z-index-group.examples/10-z-index-group.blocks/popup/_size/popup_size_bigger.css
> +:block(popup):mod(size bigger) {
Точно ) Не заметил

2016-12-21 07:20 UTC, belozer commented
что-то не пойму где ошибка.. Все тесты, кроме spec проходят.

2016-12-21 10:23 UTC, tadatuta approved these changes

2016-12-21 10:24 UTC, tadatuta commented
я порестартил тесты и они с третьего раза сошлись.
осталось переименовать файл popup_size_bigger.css в popup_size_bigger.post.css

2016-12-21 11:07 UTC, belozer commented
Уже переименовал. Я просто изменения слил в один коммит (наверное из-за этого и тесты заглючили). https://github.com/bem/bem-components/pull/1989/commits/c628b44990889874450626cc47da0426bbc3f953

2016-12-21 12:13 UTC, merged

2016-12-21 12:13 UTC, tadatuta commented
@belozer спасибо!